backend/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/



/* Login */
//Route::group(array('before'  => 'guest', array('only' => 'getIndex')), function () {
Route::controller('/login', 'LoginController');
Route::controller('/password', 'RemindersController');
Route::controller('/api/v1', 'ApiController');

//});

Route::group(array('before'  => 'auth'), function () {
	
	/* Home */
	//Route::get('/configuration', array('as'                 => 'configuration', 'uses'                 => 'CompanyController@show', 'with' => array('id' => 1)));
	Route::get('/', array('as'                 => 'index', 'uses'                 => 'HomeController@index'));
	Route::get('/sitemap.xml', array('sitemap' => 'index', 'uses' => 'HomeController@sitemap'));

	/* Resources */
	Route::controller('/logo', 'LogoController');
	Route::resource('parameter', 'ParameterController');
	Route::resource('image', 'ImageController');
	Route::resource('page', 'PageController');
	Route::resource('event', 'EventController');
	Route::resource('service', 'ServiceController');
	Route::resource('post', 'PostController');
	Route::resource('model', 'ModelTypeController');
	Route::resource('serviceaction', 'ServiceActionController');
	Route::resource('user', 'UserController');
	Route::resource('company', 'CompanyController',
		array('only' => array('show', 'edit', 'update')));
	Route::resource('oauthrequest', 'OAuthRequestController',
		array('only' => array('store')));

	Route::post('/oauthrequest', array('as'                 => 'oauthrequest', 'uses'                 => 'OAuthRequestController@create'));
	Route::resource('parameter', 'ParameterController');

	Route::get('/img_og/{id?}', array('as' => 'image', function ($id = null) {
		//
		$img_url = ($id) ? Photo::find($id) : asset('img/logo.png');
		$img = Image::make($img_url)->fit(1200, 630, function ($constraint) {
			$constraint->aspectRatio();
			//$constraint->upsize();
		});
		return $img->response('jpg');


	}));

	Route::get('/image/{id}/{width}/{height?}', array('as' => 'image', function ($id, $width, $height = null) {
		//
		$img_url = ($id) ? Photo::find($id) : asset('img/logo.png');
		$img = Image::make($img_url)->fit($width, $height, function ($constraint) {
			$constraint->aspectRatio();
			//$constraint->upsize();
		});
		return $img->response('jpg');
	}));
});

backend/app/views/pages/create.blade.php
<!-- Table -->

@include('partials.breadcrumbs', array('title'=>'Create new record', 'modelname'=> $modelname))
<ul>
    @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
    @endforeach
</ul>
 {{ Form::model( $page, array('url'=>route('page.store'), 'files' =>true)) }}
        
        <table class="table">
          <tr><th>{{ Form::label('title', 'Title') }}</th><td><input class="form-control" ng-model="title" type="text" name="title"></td></tr>
          <tr><th>{{ Form::label('slug', 'Slug') }}</th><td><input class="form-control" ng-value="title | slugify" type="text" name="slug"></td></tr>
          <tr><th>{{ Form::label('description', 'description') }}</th><td><textarea na class="form-control" name="description"></textarea></td></tr>
            <tr><th>{{ Form::label('weight', 'Weight') }}</th><td>{{ Form::number('weight', '1', array('class' => 'form-control')) }}</td></tr>
          <tr><th>{{ Form::label('content', 'content') }}</th><td><textarea class="ckeditor" name="content"></textarea></td></tr>
          <tr><th>{{ Form::label('keywords', 'keywords') }}</th><td>{{ Form::text('keywords', null, array('class' => 'form-control')) }}</td><td>* seperate by comma</td></tr>
            <tr><th>{{ Form::label('published_time', 'Published time') }}</th>
                <td><div class='input-group date datetimepicker'>
                        <input name="published_time" type='text' class="form-control" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
                    </div>
                </td>
            </tr>        </table>
        {{ Form::submit('Save record', array('class' => 'btn btn-primary')) }}
  {{ Form::close() }}

backend/app/views/pages/edit.blade.php
<!-- Table -->

@include('partials.breadcrumbs', array('title'=>'Create new record', 'modelname'=> $modelname))
<ul>
    @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
    @endforeach
</ul>
{{ Form::model($model, array('route' => array($modelname.'.update', $model->id), 'method' => 'PUT')) }}
{{ Form::submit('Opslaan', array('class' => 'btn btn-success btn-lg pull-right')) }}
        <table class="table">
          <tr><th>{{ Form::label('title', 'Title') }}</th><td>{{ Form::text('title', null, array('class' => 'form-control')) }}</td></tr>
          <tr><th>{{ Form::label('slug', 'Slug') }}</th><td><input class="form-control" placeholder="<% title | slugify %>" value="{{ $model->slug }}" type="text" name="slug"></td></tr>
          <tr><th>{{ Form::label('description', 'description') }}</th><td><textarea class="form-control" name="description" value="{{ $model->description }}">{{ $model->description }}</textarea></td></tr>
            <tr><th>{{ Form::label('weight', 'Weight') }}</th><td>{{ Form::number('weight', $model->weight, array('class' => 'form-control')) }}</td></tr>
            <tr><th>{{ Form::label('content', 'content') }}</th><td><textarea class="ckeditor" name="content" value="{{ $model->content }}">{{ $model->content }}</textarea></td></tr>
          <tr><th>{{ Form::label('keywords', 'keywords') }}</th><td>{{ Form::text('keywords', null, array('class' => 'form-control')) }}</td><td>* seperate by comma</td></tr>
            <tr><th>{{ Form::label('published_time', 'Published time') }}</th>
                <td><div class='input-group date datetimepicker'>
                        <input name="published_time" type='text' class="form-control" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
                    </div>
                </td>
            </tr>
        </table>
        {{ Form::submit('Save record', array('class' => 'btn btn-primary')) }}
  {{ Form::close() }}

backend/app/views/pages/index.blade.php
<div class="col-xs-12 col-sm-8 col-md-3 col-lg-2 pull-right">
    @include('custom_controls.btn_create', array('url'=>route($modelname.'.create')))
</div>
<!-- Table -->
<div>
    @if(count($models))
        <table class="table table-striped col-xs-12 col-sm-12 col-md-12 col-lg-12">

            <tr>
                <th>title</th>
                <th class="hidden-xs hidden-sm">description</th>
                <th class="hidden-xs">date</th>
            </tr>
            @foreach($models as $key => $value)
                <a href="{{ route($modelname.'.show', $value->id) }}">
                    <tr class="item">
                        <td> <a href="{{ route($modelname.'.show', $value->id) }}" role="button">{{{ $value->title }}}</a></td>
                        <td class="hidden-xs hidden-sm">{{ $value->description }}</td>
                        <td class="hidden-xs">{{{ $value->starting_time }}}</td>
                    </tr>
                </a>
            @endforeach
        </table>
    @else



        <div class="panel panel-info col-xs-12 col-sm-12 col-md-10 col-lg-10">
            <div class="panel-body">
                There are no records
            </div>
        </div>
    @endif
</div>

<div class="row pull-right">
    <div class="pull-right">
        {{ $models->links() }}
    </div>
</div>

backend/app/views/pages/show.blade.php
<!-- Table -->
@include('partials.breadcrumbs', array('title'=>$model->title, 'modelname'=> $modelname))
<div class="col-xs-12 col-sm-8 col-md-3 col-lg-1 pull-right">
    @include('custom_controls.btn_edit', array('url'=>route($modelname.'.edit', $model->id)))
    @include('custom_controls.btn_delete', array('url'=>route($modelname.'.destroy', $model->id)))
</div>
<div class="col-lg-10 col-md-9 col-sm-8">

    <table class="table">
        <tr><th>Title</th><td>{{{ $model->title }}}</td></tr>
        <tr><th>Description</th><td>{{{ $model->description }}}</td></tr>
        <tr><th>Content</th><td><div class="page-content">{{ $model->content }}</div></td></tr>

    </table>
</div>