backend/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/



/* Login */
//Route::group(array('before'  => 'guest', array('only' => 'getIndex')), function () {
Route::controller('/login', 'LoginController');
Route::controller('/password', 'RemindersController');
Route::controller('/api/v1', 'ApiController');

//});

Route::group(array('before'  => 'auth'), function () {
	
	/* Home */
	//Route::get('/configuration', array('as'                 => 'configuration', 'uses'                 => 'CompanyController@show', 'with' => array('id' => 1)));
	Route::get('/', array('as'                 => 'index', 'uses'                 => 'HomeController@index'));
	Route::get('/sitemap.xml', array('sitemap' => 'index', 'uses' => 'HomeController@sitemap'));

	/* Resources */
	Route::controller('/logo', 'LogoController');
	Route::resource('parameter', 'ParameterController');
	Route::resource('image', 'ImageController');
	Route::resource('page', 'PageController');
	Route::resource('event', 'EventController');
	Route::resource('service', 'ServiceController');
	Route::resource('post', 'PostController');
	Route::resource('model', 'ModelTypeController');
	Route::resource('serviceaction', 'ServiceActionController');
	Route::resource('user', 'UserController');
	Route::resource('company', 'CompanyController',
		array('only' => array('show', 'edit', 'update')));
	Route::resource('oauthrequest', 'OAuthRequestController',
		array('only' => array('store')));

	Route::post('/oauthrequest', array('as'                 => 'oauthrequest', 'uses'                 => 'OAuthRequestController@create'));
	Route::resource('parameter', 'ParameterController');

	Route::get('/img_og/{id?}', array('as' => 'image', function ($id = null) {
		//
		$img_url = ($id) ? Photo::find($id) : asset('img/logo.png');
		$img = Image::make($img_url)->fit(1200, 630, function ($constraint) {
			$constraint->aspectRatio();
			//$constraint->upsize();
		});
		return $img->response('jpg');


	}));

	Route::get('/image/{id}/{width}/{height?}', array('as' => 'image', function ($id, $width, $height = null) {
		//
		$img_url = ($id) ? Photo::find($id) : asset('img/logo.png');
		$img = Image::make($img_url)->fit($width, $height, function ($constraint) {
			$constraint->aspectRatio();
			//$constraint->upsize();
		});
		return $img->response('jpg');
	}));
});

backend/app/models/Event.php
<?php

class Agendaitem extends Eloquent {

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table     = 'events';
	public $timestamps = false;
	protected $fillable = array('title', 'description', 'published_time', 'location', 'starting_time', 'ending_time');
	public static $rules = array(
		'title' => 'required|min:2',
		'description' => 'required|min:2',
		'published_time' => 'date',
		'starting_time' => 'required|date',
		'ending_time' => 'required|date'
	);

	public function images()
	{
		return $this->morphMany('Photo', 'photoable');
	}

}

backend/app/controllers/EventController.php
<?php

class EventController extends BaseController
{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $models = Agendaitem::paginate(15);
        $modelname = 'event';
        $this->layout->content = View::make('events.index')->with(array('models' => $models, 'modelname' => $modelname));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $modelname = 'event';
        $this->layout->content = View::make('events.create')->with(array(
            'modelname' => $modelname,
        ));
    }

    /**
     * Store a newly created resource in storage.
     *17-08-2015 00:06
     * @return Response
     */
    public function store()
    {
        $input = Input::except(array('_method', '_token', 'photos'));
        //die(var_dump($input));
        //2015-08-28 05:25:02
        $validation = Validator::make($input, Agendaitem::$rules);

        if ($validation->passes()) {
            $agendaitem = new Agendaitem($input);

            $agendaitem->published_time = Input::get('starting_time');
           //die(var_dump($agendaitem));

            $agendaitem->save();
            $files = Input::file('photos');

            if ($files[0] !== null) {
                $photos = array();
                foreach ($files as $file) {
                    $rules = array(
                        'file' => 'image',
                    );
                    $validator_img = Validator::make(array('file' => $file), $rules);
                    if ($validator_img->passes()) {
                        $destinationPath = 'img/agendaitem/' . $agendaitem->id . '/';
                        $filename = str_random(12) . '.' . $file->getClientOriginalExtension();
                        $file->move($destinationPath, $filename);
                        $photo = new Photo();
                        $photo->url = $destinationPath . $filename;
                        $photo->alt = $agendaitem->title;
                        //$photo->save();
                        array_push($photos, $photo);
                    } else {
                        return Redirect::back()
                            ->withInput()
                            ->withErrors($validator_img);
                    }
                }
                $agendaitem->images()->saveMany($photos);
            }
            /* social tasks */
            foreach (ServiceAction::all() as $serviceaction) {
                $attachments = [];
                foreach($serviceaction->parameters()->get() as $parameter){
                    $attachments[$parameter->name]= $parameter->value;
                    if(strpos($parameter->value,'#')) {
                        $pattern = '#.+#';
                        $replacement = "http://www.google.com";
                        preg_replace($pattern, $replacement, $parameter->value);
                    }
                    $attachments[$parameter->name]= $parameter->value;
                }
                $url = $serviceaction->url . '?';

                foreach ($serviceaction->service()->first()->parameters() as $serviceparameter) {
                    $url = $url . $serviceparameter->name . '=' . $serviceparameter->value . '&';
                }
                $ch = curl_init();
                curl_setopt($ch, CURLOPT_URL, $url);
                curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
                curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2);
                curl_setopt($ch, CURLOPT_POST, true);
                curl_setopt($ch, CURLOPT_POSTFIELDS, $attachments);
                curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);  //to suppress the curl output
                $result = curl_exec($ch);
                curl_close($ch);
            }

            //return Redirect::back();
            Session::flash('message', 'Successfully posted');
            return Redirect::route('event.index');


        }
       return Redirect::back()
            ->withInput()
            ->withErrors($validation)
            ->with('message', 'There were validation errors.');
        Session::flash('message', 'There were errors');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        //
        $model = Agendaitem::findorfail($id);
        $modelname = 'event';
        $this->layout->content = View::make($modelname . 's.show')->with(array('model' => $model, 'modelname' => $modelname));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        //

        $model = Agendaitem::findorfail($id);
        $modelname = 'event';
        $this->layout->content = View::make($modelname . 's.edit')->with(array('model' => $model, 'modelname' => $modelname));
        //return Response::view($modelname.'.edit')->with(array('model' => $model, 'modelname' => $modelname));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     * @return Response
     */
    public function update($id)
    {
        //var_dump(Input::all());
        $input = Input::except(array('_method', '_token'));
        /*$validation = Validator::make($input, Contact::$rules);
        if ($validation->passes()) {
            $model = Contact::find($id);
            $model->update($input);
            Session::flash('message', 'Successfully edited the message!');
            return Redirect::route('admin.contact.show', $id);
        }*/
        $model = Agendaitem::find($id);
        $model->update($input);
        Session::flash('message', 'Successfully edited the event!');
        return Redirect::route('event.show', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        //
        // delete
        $model = Agendaitem::find($id);
        $model->delete();

        // redirect
        Session::flash('message', 'The event was deleted');
        return Redirect::route('event.index');
    }

}

backend/app/views/events/create.blade.php
<!-- Table -->

@include('partials.breadcrumbs', array('title'=>'Create new record', 'modelname'=> $modelname))
<ul>
    @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
    @endforeach
</ul>
 {{ Form::model( $event, array('url'=>route('event.store'), 'files' =>true)) }}
        
        <table class="table">
          <tr><th>{{ Form::label('title', 'Title') }}</th><td>{{ Form::text('title', null, array('class' => 'form-control')) }}</td></tr>
          <tr><th>{{ Form::label('intro', 'Intro') }}</th><td>{{ Form::textarea('intro', null, array('class' => 'form-control')) }}</td></tr>
          <tr><th>{{ Form::label('description', 'description') }}</th><td>{{ Form::textarea('description', null, array('class' => 'form-control')) }}</td></tr>
          <tr><th>{{ Form::label('location', 'Location') }}</th><td>{{ Form::text('location', null, array('class' => 'form-control')) }}</td></tr>
          <tr><th>{{ Form::label('starting_time', 'Begin') }}</th>
              <td><div class='input-group date datetimepicker'>
                    <input name="starting_time" type='datetime' class="form-control" data-datepicker="datepicker"/>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
              </td>
          </tr>
        <tr><th>{{ Form::label('ending_time', 'End') }}</th>
            <td><div class='input-group date datetimepicker'>
                    <input name="ending_time" type='datetime' class="form-control" data-provide="datepicker"/>
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
                </div>
            </td>
        </tr>
            <tr><th>{{ Form::label('img', 'Afbeeldingen') }}</th><td><input type="file" name="photos[]" accept="image/*" multiple></td></tr>
            <tr><th>{{ Form::label('published_time', 'Published time') }}</th>
                <td><div class='input-group date datetimepicker'>
                        <input name="published_time" type='datetime' class="form-control" data-datepicker="datepicker" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
                    </div>
                </td>
            </tr>
        </table>
        {{ Form::submit('Save record', array('class' => 'btn btn-primary')) }}
  {{ Form::close() }}

backend/app/views/events/edit.blade.php
<ul>
	@foreach($errors->all() as $error)
		<li>{{ $error }}</li>
	@endforeach
</ul>
{{ Form::model($model, array('route' => array($modelname.'.update', $model->id), 'method' => 'PUT')) }}
{{ Form::submit('Opslaan', array('class' => 'btn btn-success btn-lg pull-right')) }}
<table class="table">
	<tr><th>{{ Form::label('title', 'title') }}</th><td>{{ Form::text('title', null, array('class' => 'form-control')) }}</td></tr>
	<tr><th>{{ Form::label('description', 'description') }}</th><td>{{ Form::textarea('description', null, array('class' => 'form-control')) }}</td></tr>
	<tr><th>{{ Form::label('location', 'Location') }}</th><td>{{ Form::text('location', null, array('class' => 'form-control')) }}</td></tr>
	<tr><th>{{ Form::label('starting_time', 'Begin') }}</th>
		<td><div class='input-group date datetimepicker'>
				<input name="starting_time" type='text' class="form-control" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
			</div>
		</td>
	</tr>
	<tr><th>{{ Form::label('ending_time', 'End') }}</th>
		<td><div class='input-group date datetimepicker'>
				<input name="ending_time" type='text' class="form-control" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
			</div>
		</td>
	</tr>
</table>
{{ Form::close() }}

backend/app/views/events/index.blade.php
<div class="col-xs-12 col-sm-8 col-md-3 col-lg-2 pull-right">
    @include('custom_controls.btn_create', array('url'=>route($modelname.'.create')))
</div>
<!-- Table -->
<div>
  @if(count($models))
  <table class="table col-xs-12 col-sm-12 col-md-12 col-lg-12">

    <tr>
     <th>title</th>
     <th class="hidden-xs hidden-sm">description</th>
     <th class="hidden-xs">date</th>
   </tr>
   @foreach($models as $key => $value)
   <tr class="item">
        <td> <a href="{{ route('event.show', $value->id) }}" role="button">{{{ $value->title }}}</a></td>
        <td class="hidden-xs hidden-sm">{{{ $value->description }}}</td>
         <td class="hidden-xs">{{{ $value->starting_time }}}</td>
 </tr>
 @endforeach
</table>
@else



<div class="panel panel-info col-xs-12 col-sm-12 col-md-10 col-lg-10">
  <div class="panel-body">
    There are no records
  </div>
</div>
@endif
</div>

<div class="row pull-right">
    <div class="pull-right">
        {{ $models->links() }}
    </div>
</div>

backend/app/views/events/show.blade.php
<!-- Table -->
@include('partials.breadcrumbs', array('title'=>$model->title, 'modelname'=> $modelname))
<div class="col-xs-12 col-sm-8 col-md-3 col-lg-1 pull-right">
    @include('custom_controls.btn_edit', array('url'=>route($modelname.'.edit', $model->id)))
    @include('custom_controls.btn_delete', array('url'=>route($modelname.'.destroy', $model->id)))
</div>
<div class="col-lg-10 col-md-9 col-sm-8">

  <table class="table">
   <tr><th>Title</th><td>{{{ $model->title }}}</td></tr>
   <tr><th>Description</th><td>{{{ $model->description }}}</td></tr>
   <tr><th>Location</th><td>{{{ $model->location }}}</td></tr>
   <tr><th>Starting time</th><td>{{{ $model->starting_time }}}</td></tr>
   <tr><th>Ending time</th><td>{{{ $model->ending_time }}}</td></tr>

 </table>
</div>

@foreach($model->images as $key => $value)
    <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
        <div class="thumbnail">
            <img src="{{ asset($value->url) }}" alt="{{ $value->alt }}">
            <div class="caption">
                <h3>{{ $value->name }}</h3>

                <table class="table table-bordered">
                    <tr>
                        <td>
                            {{ Form::open(array('url' => route('image.destroy', $value->id), 'class' => ' form-inline')) }}
                            {{ Form::hidden('_method', 'DELETE') }}
                            <button type="submit" class="btn btn-danger visible-*-inline">
                                <span class="glyphicon glyphicon-remove"></span>
                            </button>
                            {{ Form::close() }}
                        </td>
                    </tr>
                </table>
                </p>
            </div>
        </div>
    </div>

@endforeach