backend/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/



/* Login */
//Route::group(array('before'  => 'guest', array('only' => 'getIndex')), function () {
Route::controller('/login', 'LoginController');
Route::controller('/password', 'RemindersController');
Route::controller('/api/v1', 'ApiController');

//});

Route::group(array('before'  => 'auth'), function () {
	
	/* Home */
	//Route::get('/configuration', array('as'                 => 'configuration', 'uses'                 => 'CompanyController@show', 'with' => array('id' => 1)));
	Route::get('/', array('as'                 => 'index', 'uses'                 => 'HomeController@index'));
	Route::get('/sitemap.xml', array('sitemap' => 'index', 'uses' => 'HomeController@sitemap'));

	/* Resources */
	Route::controller('/logo', 'LogoController');
	Route::resource('parameter', 'ParameterController');
	Route::resource('image', 'ImageController');
	Route::resource('page', 'PageController');
	Route::resource('event', 'EventController');
	Route::resource('service', 'ServiceController');
	Route::resource('post', 'PostController');
	Route::resource('model', 'ModelTypeController');
	Route::resource('serviceaction', 'ServiceActionController');
	Route::resource('user', 'UserController');
	Route::resource('company', 'CompanyController',
		array('only' => array('show', 'edit', 'update')));
	Route::resource('oauthrequest', 'OAuthRequestController',
		array('only' => array('store')));

	Route::post('/oauthrequest', array('as'                 => 'oauthrequest', 'uses'                 => 'OAuthRequestController@create'));
	Route::resource('parameter', 'ParameterController');

	Route::get('/img_og/{id?}', array('as' => 'image', function ($id = null) {
		//
		$img_url = ($id) ? Photo::find($id) : asset('img/logo.png');
		$img = Image::make($img_url)->fit(1200, 630, function ($constraint) {
			$constraint->aspectRatio();
			//$constraint->upsize();
		});
		return $img->response('jpg');


	}));

	Route::get('/image/{id}/{width}/{height?}', array('as' => 'image', function ($id, $width, $height = null) {
		//
		$img_url = ($id) ? Photo::find($id) : asset('img/logo.png');
		$img = Image::make($img_url)->fit($width, $height, function ($constraint) {
			$constraint->aspectRatio();
			//$constraint->upsize();
		});
		return $img->response('jpg');
	}));
});

backend/app/models/Service.php
<?php

use Illuminate\Database\Eloquent\SoftDeletingTrait;

class Service extends Eloquent {

	use SoftDeletingTrait;
	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table     = 'services';
	protected $dates     = ['deleted_at'];


	/*protected $dates      = ['deleted_at'];*/
	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	public function parameters()
	{
		return $this->morphMany('Parameter', 'parameterable');
	}

	public function actions()
	{
		return $this->hasMany('ServiceAction');
	}

}

backend/app/models/ServiceAction.php
<?php

use Illuminate\Database\Eloquent\SoftDeletingTrait;

class ServiceAction extends Eloquent {

	use SoftDeletingTrait;
	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table     = 'serviceactions';
	protected $dates     = ['deleted_at'];
	protected $fillable = array('name', 'description', 'url', 'request_type', 'service_id', 'modelname');
	public static  $rules = array(
		'name' => 'required',
		'description' => 'required',
		'url' => 'required',
		'request_type' => 'required',
	);


	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	public function service()
	{
		return $this->belongsTo('Service');
	}

	public function parameters() {
		return $this->morphMany('Parameter', 'parameterable');
	}

}

backend/app/controllers/ServiceController.php
<?php

class ServiceController extends \BaseController
{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        //
        $models = Service::paginate(15);
        $modelname = 'service';
        $this->layout->content = View::make('services.index')->with(array('models' => $models, 'modelname' => $modelname));

    }


    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
        $modelname = 'service';
        $this->layout->content = View::make($modelname . 's.create')->with(array('modelname' => $modelname));
    }


    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store()
    {
        //
    }


    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        //
        $model = Service::findorfail($id);
        $modelname = 'service';
        $this->layout->content = View::make($modelname . 's.show')->with(array('model' => $model, 'modelname' => $modelname));

    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     * @return Response
     */
    public function update($id)
    {
        //
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }


}

backend/app/views/services/index.blade.php
@foreach($models as $key => $value)
<a class="service" href="{{ route($modelname.'.show', array( 'id' => $value->id)) }}">
	<img src="{{ $value->logo_url }}" alt="{{ $value->name }}" width="150" class="img-thumbnail img-responsive">
</a>
@endforeach

<div class="row">
	<div class="pull-right">
		{{ $models->links() }}
	</div>
</div>

backend/app/views/services/show.blade.php
<img src="{{ asset($model->logo_url) }}" alt="{{ $model->name }}" width="150" class="img-thumbnail img-responsive">
<table>
    <tr>
        <th>Name</th>
        <td>{{ $model->name }}</td>
    </tr>
    <tr>
        <th>Website</th>
        <td>{{ $model->website_url }}</td>
    </tr>
    <tr>
        <th>Host</th>
        <td>{{ $model->host }}</td>
    </tr>
    @if($model->activated)
        <tr>
            <th>Activated</th>
            <td>Yes</td>
        </tr>
    @else
        <tr>
            <th>Activate</th>
            <td>{{ $model->activate_html }}</td>
        </tr>
    @endif

</table>

<h2>Parameters</h2>
<div class="row">

    {{ Form::open(array('url'=>route('parameter.store'))) }}
    {{ Form::hidden('parameterable_id', $model->id); }}
    {{ Form::hidden('parameterable_type', 'service'); }}
    <div class="col-lg-2">
        <label>Name</label>
    </div>
    <div class="col-lg-3">
        {{ Form::text('name', null, array('class' => 'form-control')) }}
    </div>
    <div class="col-lg-2">
        <label>Value</label>
    </div>
    <div class="col-lg-3">
        {{ Form::text('value', null, array('class' => 'form-control')) }}
    </div>
    <div class="col-lg-2">
        {{ Form::submit('Save record', array('class' => 'btn btn-primary pull-right')) }}
    </div>

    {{ Form::close() }}
</div><!-- /.row -->

@if(count(!$model->parameters))
    <table class="table col-lg-12 table-striped">
        @foreach($model->parameters as $key => $parameter)
            <tr>
                <td>{{ $parameter->name }}</td>
                <td>{{ $parameter->value }}</td>
                <td width="20">
                    {{ Form::open(array('url' => route('parameter.destroy', $parameter->id), 'class' => 'pull-right')) }}
                    {{ Form::hidden('_method', 'DELETE') }}
                    <button type="submit" class="btn btn-danger">
                        <i class="glyphicon glyphicon-remove"></i>
                    </button>
                    {{ Form::close() }}
                </td>
            </tr>
        @endforeach
    </table>
@endif

<h2>Actions</h2>
<div class="row">
    <!-- Button trigger modal -->
    <div class="col-lg-12">
        <button type="button" class="btn btn-primary pull-right" data-toggle="modal" data-target="#createActionModal">
            Add new
        </button>
    </div>
</div><!-- /.row -->

@if(count(!$model->actions))
    <table class="table col-lg-12 table-striped">
        @foreach($model->actions as $key => $action)
            <tr>
                <td>{{ $action->name }}</td>
                <td>{{ $action->value }}</td>
                <td width="20">
                    {{ Form::open(array('url' => route('serviceaction.destroy', $action->id), 'class' => ' form-inline')) }}
                    {{ Form::hidden('_method', 'DELETE') }}
                    <button type="submit" class="btn btn-danger visible-*-inline pull-right">
                        <span class="glyphicon glyphicon-remove"></span>
                    </button>
                    {{ Form::close() }}
                </td>
            </tr>
            <tr>
                <div class="row">

                    {{ Form::open(array('url'=>route('parameter.store'))) }}
                    {{ Form::hidden('parameterable_id', $action->id); }}
                    {{ Form::hidden('parameterable_type', 'serviceAction'); }}
                    <div class="col-lg-2">
                        <label>Name</label>
                    </div>
                    <div class="col-lg-3">
                        {{ Form::text('name', null, array('class' => 'form-control')) }}
                    </div>
                    <div class="col-lg-2">
                        <label>Value</label>
                    </div>
                    <div class="col-lg-3">
                        {{ Form::text('value', null, array('class' => 'form-control')) }}
                    </div>
                    <div class="col-lg-2">
                        {{ Form::submit('Add Parameter to action', array('class' => 'btn btn-primary pull-right')) }}
                    </div>

                    {{ Form::close() }}
                </div><!-- /.row -->
            </tr>
            @foreach($action->parameters as $parameter)
                <tr> <td>{{ $parameter->name }}</td> <td>{{ substr($parameter->value,0,20) }}</td><td>{{ Form::open(array('url' => route('parameter.destroy', $parameter->id), 'class' => 'pull-right')) }}
                        {{ Form::hidden('_method', 'DELETE') }}
                        <button type="submit" class="btn btn-danger">
                            <i class="glyphicon glyphicon-remove"></i>
                        </button>
                        {{ Form::close() }}</td></tr>
            @endforeach
        @endforeach
    </table>
    @endif


            <!-- Modal -->
    <div class="modal fade" id="createActionModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            {{ Form::open(array('url'=>route('serviceaction.store'))) }}
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Add new action to service</h4>
                </div>
                <div class="modal-body">
                    {{ Form::label('name', 'Name') }}{{ Form::text('name', null, array('class' => 'form-control')) }}
                    {{ Form::label('description', 'Description') }}{{ Form::text('description', null, array('class' => 'form-control')) }}
                    {{ Form::label('url', 'Url') }}{{ Form::text('url', null, array('class' => 'form-control')) }}
                    {{ Form::label('request_type', 'Request type ') }}{{ Form::select('request_type', array('POST' => 'POST', 'PUT' => 'PUT', 'GET' => 'GET'), 'POST') }}
                    {{ Form::hidden('service_id', $model->id); }}
                </div>
                <div class="modal-footer">
                    {{ Form::submit('Save', array('class' => 'btn btn-primary')) }}
                </div>
            </div>
            {{ Form::close() }}
        </div>
    </div>